trigger:
- master

pool:
  name: Sleave-server

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: TomcatDeployment@1
  inputs:
    TomcatUrl: 'http://172.174.242.141:8080/'
    Username: 'tomcat'
    Password: 'admin@123'
    Warfile: 'target/myweb-8.7.4.war'
    Context: '/myapplication'
    ServerVersion: '7OrAbove'