trigger:
- master

pool:
  name: siva-pool

steps:
- task: SonarQubePrepare@8
  inputs:
    SonarQube: 'sonarqube'
    scannerMode: 'other'
    extraProperties: |
      # Additional properties that will be passed to the scanner, 
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      sonar.projectKey=my-project_my-project_AZ6I2aAYKldlh0iuE-S_
- task: JavaToolInstaller@1
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- task: SonarQubePublish@8
  inputs:
    pollingTimeoutSec: '300'

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    sqMavenPluginVersionChoice: 'latest'
- task: TomcatDeployment@1
  inputs:
    TomcatUrl: 'http://20.115.94.105:8080/'
    Username: 'tomcat'
    Password: 'admin@123'
    Warfile: 'target/myweb-8.7.4.war'
    Context: '/myapplication'
    ServerVersion: '7OrAbove'